### ISSUE TITLE
Example fails on GPU

### ISSUE THREAD

**Issue by weidenka** [Maghoumi/pytorch-softdtw-cuda#14] opened 2021-10-05 12:11 UTC
When running the example from the README:
```python
from soft_dtw_cuda import SoftDTW
import torch
# Create the sequences
batch_size, len_x, len_y, dims = 8, 15, 12, 5
x = torch.rand((batch_size, len_x, dims), requires_grad=True)
y = torch.rand((batch_size, len_y, dims))
# Create the "criterion" object
sdtw = SoftDTW(use_cuda=True, gamma=0.1)
# Compute the loss value
loss = sdtw(x, y)  # Just like any torch.nn.xyzLoss()
# Aggregate and call backward()
loss.mean().backward()
```

I get a TypeError:
```shell
Traceback (most recent call last):
  File "test_dtw.py", line 10, in <module>
    loss = sdtw(x, y)  # Just like any torch.nn.xyzLoss()
  File "/home/dockeruser/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dockeruser/soft_dtw_cuda.py", line 352, in forward
    return func_dtw(D_xy, self.gamma, self.bandwidth)
  File "/home/dockeruser/soft_dtw_cuda.py", line 140, in forward
    compute_softdtw_cuda[B, threads_per_block](cuda.as_cuda_array(D.detach()),
  File "/home/dockeruser/env/lib/python3.7/site-packages/numba/cuda/api.py", line 74, in as_cuda_array
    raise TypeError("*obj* doesn't implement the cuda array interface.")
TypeError: *obj* doesn't implement the cuda array interface.
```

Potentially relevant packages from my env:
Cython                    0.29.24
numba                     0.54.0
torch                        1.6.0

Any suggestions?

BTW. Thanks a lot for porting to cuda!

**Comment by NAIXIL** [comment] 2021-10-20 11:57
I also encountered this situation.
win11
cuda10.2, torch==1.9.0+cu102
numba==0.54.1

**Comment by Maghoumi** [comment] 2021-10-30 23:13
Sorry for the delay in my response. I'm unable to reproduce this issue. I just setup a new `virtualenv` on my machine, with the following packages, and after pushing [this commit](https://github.com/Maghoumi/pytorch-softdtw-cuda/commit/af36395ed67db88afca8dafbe4ee1b74fca53806), everything works as expected. Here's my environment;

```
Ubuntu 20.04
torch 1.10.0+cu113
numba: 0.54.1
```

@weidenka Are you also running on Windows?

**Comment by weidenka** [comment] 2021-11-02 16:23
I ran on  Ubuntu 18.04.5

**Comment by Yutaro-Sanada** [comment] 2021-11-19 15:53
I also encountered.
However, after inserting two lines before ```sdtw = SoftDTW(use_cuda=True, gamma=0.1)```, I can run this example.
```
x = x.cuda()
y = y.cuda()
```

**Comment by NAIXIL** [comment] 2021-11-19 16:37
> I also encountered. However, after inserting two lines before `sdtw = SoftDTW(use_cuda=True, gamma=0.1)`, I can run this example.
> 
> ```
> x = x.cuda()
> y = y.cuda()
> ```
 It worked!! Thank u.

**Comment by Maghoumi** [comment] 2021-11-19 17:42
My apologies, I thought the issue was being caused by running the unit test inside `soft_dtw_cuda.py`, which explains why I was unable to reproduce locally.

@Yutaro-Sanada thanks for your PR. Will review/merge shortly.

**Comment by Maghoumi** [comment] 2021-11-19 17:49
#17 is now merged. Closing this issue.

**Closed by Maghoumi** 2021-11-19 17:49 UTC
